"""Migrations, against a real database.

The upgrade -> downgrade -> upgrade cycle is the important one. A downgrade that
leaves an artefact behind -- an enum type, an index, a sequence -- breaks the
*second* upgrade, and that is exactly the path a production
rollback-then-roll-forward takes. Testing only the forward direction would leave
that failure to be discovered during an incident.
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from orbit.infrastructure.db.models import Base

pytestmark = pytest.mark.integration

EXPECTED_TABLES = {
    "account_tokens",
    "alembic_version",
    "audit_logs",
    "chunks",
    "conversations",
    "document_processing_jobs",
    "document_tags",
    "document_versions",
    "documents",
    "folders",
    "message_citations",
    "messages",
    "refresh_tokens",
    "tags",
    "users",
    "workspace_members",
    "workspaces",
}

EXPECTED_ENUMS = {
    "account_token_purpose",
    "answer_grounding",
    "failure_kind",
    "job_status",
    "message_role",
    "message_status",
    "processing_status",
    "workspace_role",
}


async def _tables(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as conn:
        rows = await conn.execute(
            text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        )
        return {row[0] for row in rows}


async def _enums(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as conn:
        rows = await conn.execute(
            text(
                "SELECT t.typname FROM pg_type t "
                "JOIN pg_namespace n ON n.oid = t.typnamespace "
                "WHERE t.typtype = 'e' AND n.nspname = 'public'"
            )
        )
        return {row[0] for row in rows}


async def _run(engine: AsyncEngine, revision: str) -> None:
    def go(connection: object) -> None:
        config = Config("alembic.ini")
        config.attributes["connection"] = connection
        command.upgrade(config, revision) if revision != "base" else command.downgrade(
            config, "base"
        )

    async with engine.begin() as conn:
        await conn.run_sync(go)


class TestCleanUpgrade:
    """The `migrated_engine` fixture already dropped the schema and migrated it
    from empty, so reaching these assertions at all proves a clean upgrade."""

    async def test_creates_every_expected_table(self, migrated_engine: AsyncEngine) -> None:
        assert await _tables(migrated_engine) == EXPECTED_TABLES

    async def test_creates_every_enum_type(self, migrated_engine: AsyncEngine) -> None:
        assert (await _enums(migrated_engine)) >= EXPECTED_ENUMS

    async def test_stamps_the_head_revision(self, migrated_engine: AsyncEngine) -> None:
        async with migrated_engine.connect() as conn:
            revision = await conn.scalar(text("SELECT version_num FROM alembic_version"))
        # Read from the script directory rather than hard-coded, so adding a
        # migration cannot leave this asserting a revision that is no longer head.
        assert revision == ScriptDirectory.from_config(Config("alembic.ini")).get_current_head()

    async def test_pgvector_column_has_the_configured_dimension(
        self, migrated_engine: AsyncEngine
    ) -> None:
        """The dimension is schema, not configuration (ADR-0007). If this ever
        disagrees with ORBIT_EMBEDDING_DIMENSIONS, embeddings are corrupt."""
        async with migrated_engine.connect() as conn:
            declared = await conn.scalar(
                text(
                    "SELECT format_type(atttypid, atttypmod) FROM pg_attribute "
                    "WHERE attrelid = 'chunks'::regclass AND attname = 'embedding'"
                )
            )
        assert declared == "vector(1536)"

    async def test_search_vector_is_a_generated_column(self, migrated_engine: AsyncEngine) -> None:
        """Generated by the database, so the lexical index cannot drift from the
        text it indexes."""
        async with migrated_engine.connect() as conn:
            generated = await conn.scalar(
                text(
                    # `attgenerated` is the single-byte `"char"` type, which
                    # asyncpg returns as bytes; cast so the comparison is text.
                    "SELECT attgenerated::text FROM pg_attribute "
                    "WHERE attrelid = 'chunks'::regclass AND attname = 'search_vector'"
                )
            )
        assert generated == "s", "search_vector must be STORED GENERATED"

    async def test_hnsw_index_exists_with_cosine_operator(
        self, migrated_engine: AsyncEngine
    ) -> None:
        async with migrated_engine.connect() as conn:
            definition = await conn.scalar(
                text("SELECT indexdef FROM pg_indexes WHERE indexname = 'ix_chunks_embedding_hnsw'")
            )
        assert definition is not None
        assert "USING hnsw" in definition
        assert "vector_cosine_ops" in definition


class TestDowngradeAndReupgrade:
    """The rollback path.

    This test deliberately mutates the shared schema and restores it, so it is
    ordered last within the module by name and leaves the database at `head`.
    """

    async def test_downgrade_removes_everything_then_upgrade_restores_it(
        self, migrated_engine: AsyncEngine
    ) -> None:
        await _run(migrated_engine, "base")

        remaining = await _tables(migrated_engine)
        # `alembic_version` survives a downgrade to base by design.
        assert remaining <= {"alembic_version"}, f"downgrade left tables behind: {remaining}"

        leftover_enums = await _enums(migrated_engine) & EXPECTED_ENUMS
        assert not leftover_enums, (
            f"downgrade left enum types behind: {leftover_enums}. The next upgrade "
            f"would fail with 'type already exists' -- the exact failure a "
            f"rollback-then-roll-forward hits."
        )

        # The second upgrade is what a roll-forward after a rollback does.
        await _run(migrated_engine, "head")
        assert await _tables(migrated_engine) == EXPECTED_TABLES


class TestModelMigrationParity:
    """The migration and the models must describe the same schema.

    Drift here is silent and expensive: the application would run against a
    schema its queries were not written for.
    """

    async def test_no_pending_changes(self, migrated_engine: AsyncEngine) -> None:
        def compare(connection: object) -> list[tuple[object, ...]]:
            context = MigrationContext.configure(
                connection,  # type: ignore[arg-type]
                opts={"compare_type": True},
            )
            return list(compare_metadata(context, Base.metadata))

        async with migrated_engine.connect() as conn:
            diff = await conn.run_sync(compare)

        # Alembic reports index differences for expression-based indexes it
        # cannot round-trip through reflection; those are filtered so the test
        # fails on genuine drift rather than on a known reflection limitation.
        meaningful = [
            change
            for change in diff
            if not (isinstance(change, tuple) and str(change[0]).endswith("_index"))
        ]
        assert not meaningful, f"models and migration have drifted: {meaningful}"
