"""Object storage port (ADR-0011).

The application depends on this Protocol, never on `boto3` or any other SDK.
That is not a style preference: `application` is forbidden by
`backend/.importlinter` from importing `orbit.infrastructure` at all, so a use
case that called `boto3` directly would fail to type-check as a layering
violation, not merely read badly.

Every method takes a `str` key. Keys are always generated by
`core/storage_keys.py` from server-controlled identifiers -- a workspace id, a
document id, a version id -- and never from user input, which is what makes
path traversal unrepresentable rather than merely filtered (see
`core/uploads.py` for the input validation that runs before a key is ever
built).

Streams, never `bytes`. A signature accepting `bytes` guarantees that some
caller eventually loads a full upload into memory, and that concurrent uploads
become a memory-exhaustion incident. Every method that moves file content
therefore takes or returns an `AsyncIterator[bytes]`.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import timedelta
from typing import Protocol


@dataclass(frozen=True, slots=True)
class StoredObject:
    """What the storage layer can attest to after a write.

    Deliberately does not carry a content hash: computing one is a validation
    concern, and validation is business logic that belongs in the application
    layer (`core/uploads.py`'s hashing stream wrapper), not in the storage
    adapter. This type reports only what storage itself knows -- the key it
    wrote to and how many bytes it actually received -- so the two facts can be
    compared against what the caller believes it sent, as a defense against a
    truncated or silently-partial write.
    """

    key: str
    byte_size: int


@dataclass(frozen=True, slots=True)
class ObjectSummary:
    """One entry from a prefix listing, for the orphan sweep."""

    key: str
    byte_size: int


class ObjectStorage(Protocol):
    """S3-compatible object storage: MinIO in development, AWS S3 in production.

    Every method is safe to call for a key that was never generated by this
    process -- there is no method that trusts a caller-supplied path, because
    there is no method that treats a path as anything but an opaque key.
    """

    async def put_stream(
        self,
        key: str,
        stream: AsyncIterator[bytes],
        *,
        content_type: str,
    ) -> StoredObject:
        """Write a stream to `key`, failing if `key` already holds an object.

        The "already holds an object" refusal is deliberate, not incidental:
        keys are fresh UUIDs minted per version, so a collision here is not a
        legitimate re-upload -- it is either a bug that reused a key or, in the
        adversarial case, an attempt to overwrite content a caller does not
        own. Either way, silently succeeding is the wrong behaviour.
        """
        ...

    def open_stream(self, key: str) -> AsyncIterator[bytes]:
        """Read `key` back as a stream.

        Not called by any use case yet -- **no API route proxies a download**;
        see `presigned_get_url` for why. This exists for the document-processing
        worker (a later milestone), which must revalidate the complete object
        before parsing it: the upload-time check in `core/uploads.py` inspects
        only the first chunk, so it is a fast rejection, not the security
        boundary (ADR-0011).
        """
        ...

    async def presigned_get_url(
        self,
        key: str,
        *,
        ttl: timedelta,
        download_filename: str,
    ) -> str:
        """A short-lived, single-object URL the browser fetches directly.

        This is the whole answer to "never expose private storage credentials
        to the frontend": the caller receives a capability scoped to one
        object and one expiry, never the access key that could mint another
        one. `download_filename` becomes the presigned URL's
        `Content-Disposition`, so a browser saves the file under the name the
        uploader gave it rather than the opaque storage key.
        """
        ...

    async def delete(self, key: str) -> None:
        """Remove an object. Idempotent: deleting an absent key is not an error.

        Idempotence matters here specifically because it is called from two
        failure-cleanup paths (a losing deduplication race, an aborted
        multipart upload) where "was it already gone" is not a question worth
        answering before deleting.
        """
        ...

    async def exists(self, key: str) -> bool:
        """Whether `key` currently holds an object.

        Used before minting a download URL for a version whose row survived
        but whose object did not (a prior aborted delete, a hand-edited
        database, a bug) -- so the failure is a clean 404 from ORBIT rather
        than an opaque failure the moment the browser follows the URL.
        """
        ...

    def list_keys(self, prefix: str) -> AsyncIterator[ObjectSummary]:
        """Every object under `prefix`, for the orphan sweep.

        `prefix` is workspace-scoped (`core/storage_keys.py`'s
        `workspace_prefix`), never the whole bucket -- a sweep that walked
        every tenant's objects to reconcile one workspace would be quadratic
        in the number of workspaces for no reason.
        """
        ...
